### ISSUE TITLE
give the library a nicer name

### ISSUE THREAD

**Issue by tesselode** [Positive07/wonderland.lua#1]
animate.lua is a pretty generic name. open source projects need unique and short names, right? maybe even a human name? like anna?

**Comment by tesselode** [comment]
then rename `animate.new()` to `anna.mate()`

**Comment by tesselode** [comment]
jk don't do that

**Comment by pablomayobre** [comment]
Yeah, that's something I have been thinking too, what about `animo.lua`?

_Animo_ is Spanish (my native language) for _Mood_

**Comment by tesselode** [comment]
maybe? that's still pretty close to kikito's anim8, though
